### ISSUE TITLE
Problem iAlarm Event

### ISSUE THREAD

**Issue by Didier57** [maxill1/node-red-contrib-ialarm#5]
Hello,
I just installed NODE-RED on Docker.
I am also using Node-red on a Windows PC and iAlarm Events is working.
But on Docker I still get this error when i clic on timestamp
![image](https://user-images.githubusercontent.com/76200115/105321128-59508200-5bc7-11eb-83f4-db7b44abd74e.png)

```21 Jan 08:51:28 - [red] Uncaught Exception:

21 Jan 08:51:28 - TypeError: content.forEach is not a function

    at parse (/data/node_modules/ialarm/node_modules/cheerio/lib/parse.js:38:15)

    at Function.exports.load (/data/node_modules/ialarm/node_modules/cheerio/lib/static.js:39:14)

    at Node.<anonymous> (/data/node_modules/ialarm/ialarm.js:245:34)

    at initialize.exports.each (/data/node_modules/ialarm/node_modules/cheerio/lib/api/traversing.js:562:24)

    at /data/node_modules/ialarm/ialarm.js:242:19

    at IncomingMessage.<anonymous> (/data/node_modules/ialarm/ialarm.js:133:13)

    at IncomingMessage.emit (events.js:203:15)

    at endReadableNT (_stream_readable.js:1145:12)

    at process._tickCallback (internal/process/next_tick.js:63:19)

npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! node-red-docker@1.2.7 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the node-red-docker@1.2.7 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /data/.npm/_logs/2021-01-21T07_51_28_813Z-debug.log```

**Comment by Didier57** [comment]
This is the log file /data/.npm/_logs/2021-01-21T07_51_28_813Z-debug.log

```info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   '--no-update-notifier',
1 verbose cli   '--no-fund',
1 verbose cli   'start',
1 verbose cli   '--cache',
1 verbose cli   '/data/.npm',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data' ]
2 info using npm@6.14.10
3 info using node@v10.23.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle node-red-docker@1.2.7~prestart: node-red-docker@1.2.7
6 info lifecycle node-red-docker@1.2.7~start: node-red-docker@1.2.7
7 verbose lifecycle node-red-docker@1.2.7~start: unsafe-perm in lifecycle true
8 verbose lifecycle node-red-docker@1.2.7~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle node-red-docker@1.2.7~start: CWD: /usr/src/node-red
10 silly lifecycle node-red-docker@1.2.7~start: Args: [ '-c',
10 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"' ]
11 silly lifecycle node-red-docker@1.2.7~start: Returned: code: 1  signal: null
12 info lifecycle node-red-docker@1.2.7~start: Failed to exec start script
13 verbose stack Error: node-red-docker@1.2.7 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid node-red-docker@1.2.7
15 verbose cwd /usr/src/node-red
16 verbose Linux 4.4.59+
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "--no-update-notifier" "--no-fund" "start" "--cache" "/data/.npm" "--" "--userDir" "/data"
18 verbose node v10.23.1
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error node-red-docker@1.2.7 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
22 error Exit status 1
23 error Failed at the node-red-docker@1.2.7 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]```

**Comment by Didier57** [comment]
Hello, 

I solved the problem by deleting the folder /node_modules/ialarm/node_modules/cheerio
